### PR TITLE
Apiarist's Pipe GUI fix

### LINKED ISSUE #9230: Apiarist's Pipe UI is not visible
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.1.2.0

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Tried to open apiarists pipe by right clicking on it.

In previous versions, I would expect something like this...
image

### The Reality

No UI is shown when there normally would be one.
image

### Your Proposal

Revert UI functionality to how it was previously.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by YannickMG**
This fixes GTNewHorizons/GT-New-Horizons-Modpack#9230.

Please confirm whether the previous commit was trying to fix a different issue that this would re-introduce.

### CODE REVIEW

**Comment by bombcar** [comment]
@Dream-Master that commit was yours - any insight what it was trying to do?

**Comment by Glease** [comment]
Presumably just to make it compile.

**Comment by Dream-Master** [comment]
@bombcar idk what commit you refer here?

**Comment by Dream-Master** [comment]
i just pull over from original repo. asie fix some stuff but maybe some are forgotten or/and not fixed

**Comment by YannickMG** [comment]
> @bombcar idk what commit you refer here?

Sorry could have been clearer. This reverts commit 366fe99.

**Comment by Dream-Master** [comment]
@YannickMG does it compile with this change ?

**Comment by YannickMG** [comment]
It certainly does with the included build script, and it appears to restore the missing UI.

**Review by Dream-Master — APPROVED** [review]

**Comment by Dream-Master** [comment]
So it not builds on jenkins @YannickMG can you setup the buildscript for it?
http://jenkins.usrv.eu:8080/job/BuildCraftCompat/

**Comment by YannickMG** [comment]
I could take a look at it later today, haven't messed with Jenkins yet though. I do see it doesn't even seem to be able to start compiling due to not finding the graddle wrapper?

08:01:48 [Gradle] - Launching build.
08:01:48 FATAL: The Gradle wrapper has not been found in these directories: /var/lib/jenkins/workspace/BuildCraftCompat
08:01:48 Build step 'Invoke Gradle script' marked build as failure

**Comment by YannickMG** [comment]
> So it not builds on jenkins @YannickMG can you setup the buildscript for it? http://jenkins.usrv.eu:8080/job/BuildCraftCompat/

Wait I see that this last build triggered on the master branch before you reorganized them. What if you trigger a new build after that reorg?

**Comment by SinTh0r4s** [comment]
I'll take a look at migrating the build script tomorrow if I can ;-)

**Comment by YannickMG** [comment]
> I'll take a look at migrating the build script tomorrow if I can ;-)

Thanks! Right now pulling the current master branch and running the "setupDecompWorkspace" (or "setupCI") and "build" tasks works for me. The "runClient" task not so much.

**Pull request merged**
